instance_ami = "ami-03e88be9ecff64781"
instance_type = "t2.medium"
vpc_id = "insert vpc id here"
az1_subnet = "insert subnet id here"
az2_subnet = "insert subnet id here"
sentry_cert_arn = "insert certificte arn here"